name: C# Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up C#
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8'

      - run: dotnet add package xunit
      - run: dotnet restore 
      - run: dotnet test
